# Generated by Django 4.0.1 on 2022-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Unasigned'), ('1', 'Staff'), ('2', 'Supervisor'), ('3', 'Administrator'), ('4', 'System Administrator')], default='0', max_length=1),
        ),
    ]
